export const activities = [
  {
    _id: "60af884c2f9f9b1d2c8d9e11",
    name: "روحى",
    description: "الروحى",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e12",
    name: "المحفوظات و القبطى",
    description: "الكتاب المقدس و المحفوظات",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e13",
    name: "البحوث",
    description: "البحوث",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e14",
    name: "الالحان و التسبحة",
    description: "الالحان و التسبحة",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1d",
    name: " رياضى بنات",
    description: "رياضى بنات",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e16",
    name: "الانشطة الكنسية",
    description: "الانشطة الكنسية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e17",
    name: "ألادبية",
    description: "ألادبية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e18",
    name: "الثقافية",
    description: "الثقافية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e19",
    name: "الفنون التشكيلية",
    description: "الفنون التشكيلية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1a",
    name: "الكمبيوتر",
    description: "الكمبيوتر",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1b",
    name: "الاعلامية",
    description: "الاعلامية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1c",
    name: "الابتكارية الهندسية و العلمية",
    description: "الابتكارية الهندسية و العلمية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e15",
    name: "قلب واحد",
    description: "قلب واحد",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1e",
    name: "رياضي بنين",
    description: "الرياضية",
  },
];

export const FormTemplates =
  [
    // روحى : (60af884c2f9f9b1d2c8d9e11)
    {
      "_id": "664b48137565dd25fca12224",
      "name": "روحى جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e11",
      "description": "استمارة لتسجيل الأنشطة الروحي الجماعي",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": true,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12225",
      "name": "روحى فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e11",
      "description": "استمارة لتسجيل الأنشطة الروحي الفردي",
      "fields": [
        {
          "order": 1,
          "name": "الرب نورى و خلاصى",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "هل يمكن ان تطفئ الشمس",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 3,
          "name": "شخص ورى جدا",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 4,
          "name": "خلقنا ذكور واناث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 5,
          "name": "التقليد الكنسى",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 6,
          "name": "فردى كرازة",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
      ],
    },
    // المحفوظات و القبطى : (60af884c2f9f9b1d2c8d9e12)
    {
      "_id": "664b48137565dd25fca12226",
      "name": "المحفوظات و القبطى",
      "activityId": "60af884c2f9f9b1d2c8d9e12",
      "description": "استمارة لتسجيل الأنشطة المحفوظات و القبطى",
      "fields": [
        {
          "order": 1,
          "name": "المحفوظات",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "قبطى م1",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 3,
          "name": "قبطى م2",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
      ],
    },
    // الالحان و التسبحة : (60af884c2f9f9b1d2c8d9e14)
    {
      "_id": "664b48137565dd25fca12227",
      "name": "الالحان و التسبحة",
      "activityId": "60af884c2f9f9b1d2c8d9e14",
      "description": "استمارة لتسجيل الأنشطة الالحان و التسبحة",
      "fields": [
        {
          "order": 1,
          "name": "المستوى الاول",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "المستوى الثانى",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 3,
          "name": "مستوى المتميزين الجماعى",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    // رياضي بنين : (60af884c2f9f9b1d2c8d9e1e)
    {
      "_id": "664b48137565dd25fca12228",
      "name": "رياضى بنين جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1e",
      "description": "استمارة لتسجيل  لكرة القدم و كرة الطائرة",
      "fields": [
        {
          "order": 1,
          "name": "كرة القدم",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 150,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "كرة طائرة",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12229",
      "name": "رياضى بنين فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1e",
      "description": "شطرنج - تنس طاولة - كونيكت - بلياردو - دومينو - بلاي ستيشن",
      "fields": [
        {
          "order": 1,
          "name": "شطرنج",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 2,
          "name": "تنس طاولة",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 3,
          "name": "كونيكت",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 4,
          "name": "بلياردو",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 5,
          "name": "دومينو",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 6,
          "name": "بلاي ستيشن",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // رياضى بنات : (60af884c2f9f9b1d2c8d9e1d)
    {
      "_id": "664b48137565dd25fca12239",
      "name": "رياضى بنات جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1d",
      "description": "استمارة لتسجيل  لكرة القدم و كرة الطائرة",
      "fields": [
        {
          "order": 1,
          "name": "كرة القدم",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 150,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "كرة طائرة",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12230",
      "name": "رياضى بنات فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1d",
      "description": "شطرنج - تنس طاولة - كونيكت - دومينو",
      "fields": [
        {
          "order": 1,
          "name": "شطرنج",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 2,
          "name": "تنس طاولة",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 3,
          "name": "كونيكت",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 4,
          "name": "دومينو",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // الابحاث : (60af884c2f9f9b1d2c8d9e13)
    {
      "_id": "664b48137565dd25fca12231",
      "name": "نظرى",
      "activityId": "60af884c2f9f9b1d2c8d9e13",
      "description": "استمارة لتسجيل الأبحاث النظرية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الابحاث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 10,
            "maxNumber": 50,
            "nameTitle": "اسم الباحث",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12232",
      "name": "ميدانى",
      "activityId": "60af884c2f9f9b1d2c8d9e13",
      "description": "استمارة لتسجيل الأبحاث الميدانية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الابحاث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
            "nameTitle": "اسم الباحث",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12233",
      "name": "ثقافى",
      "activityId": "60af884c2f9f9b1d2c8d9e13",
      "description": "استمارة لتسجيل الأبحاث الثقافية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الابحاث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 15,
            "maxNumber": 50,
            "nameTitle": "اسم الباحث",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // الانشطة الكنسية : (60af884c2f9f9b1d2c8d9e16)
    {
      "_id": "664b48137565dd25fca12234",
      "name": "مسرح تقليدى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل المسرح التقليدى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12235",
      "name": "مسرح المايم",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل مسرح المايم",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12236",
      "name": "مونو دراما",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل المونو دراما",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12237",
      "name": "ديو دراما",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل الديو دراما",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 200,
            "maxNumber": 50,
            "nameTitle": "الفريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 2,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12238",
      "name": "الحكى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل الحكى",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12240",
      "name": "مسرح قبطى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل مسرح قبطى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12241",
      "name": "كورال مستوى اول",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل كورال مستوى اول",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12242",
      "name": "كورال مستوى اول متميز",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل كورال مستوى اول متميز",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12243",
      "name": "كورال مستوى ثانى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل كورال مستوى ثانى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12244",
      "name": "كورال مستوى ثانى متميز",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل كورال مستوى ثانى متميز",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12245",
      "name": "كانتاتا",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل كانتاتا",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12246",
      "name": "الاوبريت",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة الاوبريت",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12247",
      "name": "ترنيم فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة ترنيم فردى",
      "fields": [
        {
          "order": 1,
          "name": "اسم المشارك",
          "description": "ادخل اسم المشارك",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12248",
      "name": "عزف فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة عزف فردى",
      "fields": [
        {
          "order": 1,
          "name": "اسم المشارك",
          "description": "ادخل اسم المشارك",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12249",
      "name": "عزف جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة عزف جماعى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم الفريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12250",
      "name": "تاليف موسيقى مستوى اول",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة تاليف موسيقى مستوى اول",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12251",
      "name": "تاليف موسيقى مستوى ثانى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة تاليف موسيقى مستوى ثانى",
      "isNumber": true,
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // الادبية : (60af884c2f9f9b1d2c8d9e17)
    {
      "_id": "664b48137565dd25fca12252",
      "name": "شعر",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل الشعر",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12253",
      "name": "ترنيمة عقيدية",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل ترنيمة عقيدية",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12254",
      "name": "قصة قصيرة",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل قصة قصيرة",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12255",
      "name": "رواية",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل رواية",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12256",
      "name": "نص مسرحى",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل نص مسرحى",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12257",
      "name": "سيناريو",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل سيناريو",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12258",
      "name": "ريفيو ادبى",
      "activityId": "60af884c2f9f9b1d2c8d9e17",
      "description": "استمارة لتسجيل ريفيو ادبى",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // الثقافية : (60af884c2f9f9b1d2c8d9e18)
    {
      "_id": "664b48137565dd25fca12259",
      "name": "تلخيص كتاب",
      "activityId": "60af884c2f9f9b1d2c8d9e18",
      "description": "استمارة لتسجيل تلخيص كتاب",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12260",
      "name": "مجلة حائط",
      "activityId": "60af884c2f9f9b1d2c8d9e18",
      "description": "استمارة لتسجيل مجلة حائط",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12261",
      "name": "مجلة ورقية",
      "activityId": "60af884c2f9f9b1d2c8d9e18",
      "description": "استمارة لتسجيل مجلة ورقية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12262",
      "name": "تقرير ميدانى",
      "activityId": "60af884c2f9f9b1d2c8d9e18",
      "description": "استمارة لتسجيل تقرير ميدانى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12263",
      "name": "مقال",
      "activityId": "60af884c2f9f9b1d2c8d9e18",
      "description": "استمارة لتسجيل مقال",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    // الكمبيوتر : (60af884c2f9f9b1d2c8d9e1a)
    {
      "_id": "664b48137565dd25fca12264",
      "name": "مالتى ميديا فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1a",
      "description": "استمارة لتسجيل مالتى ميديا فردى",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12265",
      "name": "برمجة فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1a",
      "description": "استمارة لتسجيل برمجة",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12266",
      "name": "جرافيك فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1a",
      "description": "استمارة لتسجيل جرافيك",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12267",
      "name": "مالتى ميديا جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1a",
      "description": "استمارة لتسجيل مالتى ميديا جماعى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "الفريق",
            "minRequiredNames": 4,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12268",
      "name": "برمجة جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1a",
      "description": "استمارة لتسجيل برمجة جماعى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "الفريق",
            "minRequiredNames": 4,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12269",
      "name": "جرافيك جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1a",
      "description": "استمارة لتسجيل جرافيك جماعى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "الفريق",
            "minRequiredNames": 4,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    // الاعلامية : (60af884c2f9f9b1d2c8d9e1b)
    {
      "_id": "664b48137565dd25fca12270",
      "name": "فيلم تسجيلى",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمارة لتسجيل فيلم تسجيلى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12271",
      "name": "برنامج تليفزيونى",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمارة لتسجيل برنامج تليفزيونى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12272",
      "name": "برنامج إذاعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمار لتسجيل برنامج إذاعى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12273",
      "name": "ترنيمة مصورة",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمارة لتسجيل ترنيمة مصورة",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12274",
      "name": "إعلان تليفزيونى",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمارة لتسجيل إعلان تليفزيونى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12275",
      "name": "عمل درامى",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمار لتسجيل عمل درامى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12276",
      "name": "جرافكس",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمارة لتسجيل جرافكس",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12277",
      "name": "تقرير تليفزيونى",
      "activityId": "60af884c2f9f9b1d2c8d9e1b",
      "description": "استمارة لتسجيل تقرير تليفزيونى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    // الابتكارية الهندسية و العلمية: (60af884c2f9f9b1d2c8d9e1c)
    {
      "_id": "664b48137565dd25fca12278",
      "name": "البرمجة والكهرباء والميكانيكا",
      "activityId": "60af884c2f9f9b1d2c8d9e1c",
      "description": "استمارة لتسجيل البرمجة والكهرباء والميكانيكا",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "الفريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12279",
      "name": "العمارة",
      "activityId": "60af884c2f9f9b1d2c8d9e1c",
      "description": "استمارة لتسجيل العمارة",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "الفريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12280",
      "name": "المستوى المتخصص",
      "activityId": "60af884c2f9f9b1d2c8d9e1c",
      "description": "استمارة لتسجيل المستوى المتخصص",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "الفريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    // فنون تشكيلية : (60af884c2f9f9b1d2c8d9e19)
    {
      "_id": "664b48137565dd25fca12281",
      "name": "تصوير فوتوغرافى",
      "activityId": "60af884c2f9f9b1d2c8d9e19",
      "description": "استمارة لتسجيل تصوير فوتوغرافى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12282",
      "name": "اشغال فردي وجماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e19",
      "description": "استمارة لتسجيل اشغال فردي وجماعى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "فريق",
            "minRequiredNames": 1,
            "maxRequiredNames": 10,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12283",
      "name": "كاريكاتير",
      "activityId": "60af884c2f9f9b1d2c8d9e19",
      "description": "استمارة لتسجيل كاريكاتير",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12284",
      "name": "كوميكس",
      "activityId": "60af884c2f9f9b1d2c8d9e19",
      "description": "استمارة لتسجيل كوميكس",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12285",
      "name": "عرض ازياء",
      "activityId": "60af884c2f9f9b1d2c8d9e19",
      "description": "استمارة لتسجيل عرض ازياء",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12286",
      "name": "رسم",
      "activityId": "60af884c2f9f9b1d2c8d9e19",
      "description": "استمارة لتسجيل رسم",
      "fields": [
        {
          "order": 1,
          "name": "رصاص",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 2,
          "name": "الوان خشب",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 3,
          "name": "الوان مائى",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 4,
          "name": "جاف",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
            "nameTitle": "المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // قلب واحد : (60af884c2f9f9b1d2c8d9e15)
    {
      "_id": "664b48137565dd25fca12287",
      "name": "قلب واحد",
      "activityId": "60af884c2f9f9b1d2c8d9e15",
      "description": "الكنيسة المشاركة لايجوز ان تكون قد اشتركت فى المرحلة الابتدائية او الاعدادية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الاعمال",
          "description": "ادخل عدد الاعمال",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 10,
          },
        },
      ],
    },
  ];