export const activities = [
  {
    _id: "60af884c2f9f9b1d2c8d9e11",
    name: "روحى",
    description: "الروحى",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e12",
    name: "المحفوظات و القبطى",
    description: "الكتاب المقدس و المحفوظات",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e13",
    name: "البحوث",
    description: "البحوث",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e14",
    name: "الالحان و التسبحة",
    description: "الالحان و التسبحة",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1d",
    name: " رياضى بنات",
    description: "رياضى بنات",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e16",
    name: "الانشطة الكنسية",
    description: "الانشطة الكنسية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e17",
    name: "ألادبية",
    description: "ألادبية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e18",
    name: "الثقافية",
    description: "الثقافية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e19",
    name: "الفنون التشكيلية",
    description: "الفنون التشكيلية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1a",
    name: "الكمبيوتر",
    description: "الكمبيوتر",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1b",
    name: "الاعلامية",
    description: "الاعلامية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1c",
    name: "الابتكارية الهندسية و العلمية",
    description: "الابتكارية الهندسية و العلمية",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e15",
    name: "قلب واحد",
    description: "قلب واحد",
  },
  {
    _id: "60af884c2f9f9b1d2c8d9e1e",
    name: "رياضي بنين",
    description: "الرياضية",
  },
];

export const FormTemplates =
  [
    // روحى : (60af884c2f9f9b1d2c8d9e11)
    {
      "_id": "664b48137565dd25fca12224",
      "name": "روحى جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e11",
      "description": "استمارة لتسجيل الأنشطة الروحي الجماعي",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": true,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12225",
      "name": "روحى فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e11",
      "description": "استمارة لتسجيل الأنشطة الروحي الفردي",
      "fields": [
        {
          "order": 1,
          "name": "الرب نورى و خلاصى",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "هل يمكن ان تطفئ الشمس",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 3,
          "name": "شخص ورى جدا",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 4,
          "name": "خلقنا ذكور واناث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 5,
          "name": "التقليد الكنسى",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
        {
          "order": 6,
          "name": "فردى كرازة",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
          },
        },
      ],
    },
    // المحفوظات و القبطى : (60af884c2f9f9b1d2c8d9e12)
    {
      "_id": "664b48137565dd25fca12226",
      "name": "المحفوظات و القبطى",
      "activityId": "60af884c2f9f9b1d2c8d9e12",
      "description": "استمارة لتسجيل الأنشطة المحفوظات و القبطى",
      "fields": [
        {
          "order": 1,
          "name": "المحفوظات",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "قبطى م1",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 3,
          "name": "قبطى م2",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
      ],
    },
    // الالحان و التسبحة : (60af884c2f9f9b1d2c8d9e14)
    {
      "_id": "664b48137565dd25fca12227",
      "name": "الالحان و التسبحة",
      "activityId": "60af884c2f9f9b1d2c8d9e14",
      "description": "استمارة لتسجيل الأنشطة الالحان و التسبحة",
      "fields": [
        {
          "order": 1,
          "name": "المستوى الاول",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "المستوى الثانى",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 25,
            "maxNumber": 50,
          },
        },
        {
          "order": 3,
          "name": "مستوى المتميزين الجماعى",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    // رياضي بنين : (60af884c2f9f9b1d2c8d9e1e)
    {
      "_id": "664b48137565dd25fca12228",
      "name": "رياضى بنين جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1e",
      "description": "استمارة لتسجيل  لكرة القدم و كرة الطائرة",
      "fields": [
        {
          "order": 1,
          "name": "كرة القدم",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 150,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "كرة طائرة",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12229",
      "name": "رياضى بنين فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1e",
      "description": "شطرنج - تنس طاولة - كونيكت - بلياردو - دومينو - بلاي ستيشن",
      "fields": [
        {
          "order": 1,
          "name": "شطرنج",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 2,
          "name": "تنس طاولة",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 3,
          "name": "كونيكت",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 4,
          "name": "بلياردو",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 5,
          "name": "دومينو",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 6,
          "name": "بلاي ستيشن",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعب",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // رياضى بنات : (60af884c2f9f9b1d2c8d9e1d)
    {
      "_id": "664b48137565dd25fca12228",
      "name": "رياضى بنات جماعى",
      "activityId": "60af884c2f9f9b1d2c8d9e1d",
      "description": "استمارة لتسجيل  لكرة القدم و كرة الطائرة",
      "fields": [
        {
          "order": 1,
          "name": "كرة القدم",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 150,
            "maxNumber": 50,
          },
        },
        {
          "order": 2,
          "name": "كرة طائرة",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12229",
      "name": "رياضى بنات فردى",
      "activityId": "60af884c2f9f9b1d2c8d9e1d",
      "description": "شطرنج - تنس طاولة - كونيكت - دومينو",
      "fields": [
        {
          "order": 1,
          "name": "شطرنج",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 2,
          "name": "تنس طاولة",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 3,
          "name": "كونيكت",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
        {
          "order": 4,
          "name": "دومينو",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "nameTitle": "اسم اللاعبة",
            "price": 20,
            "maxNumber": 50,
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // الابحاث : (60af884c2f9f9b1d2c8d9e13)
    {
      "_id": "664b48137565dd25fca12230",
      "name": "نظرى",
      "activityId": "60af884c2f9f9b1d2c8d9e13",
      "description": "استمارة لتسجيل الأبحاث النظرية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الابحاث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 10,
            "maxNumber": 50,
            "nameTitle": "اسم الباحث",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12231",
      "name": "ميدانى",
      "activityId": "60af884c2f9f9b1d2c8d9e13",
      "description": "استمارة لتسجيل الأبحاث الميدانية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الابحاث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 20,
            "maxNumber": 50,
            "nameTitle": "اسم الباحث",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12232",
      "name": "ثقافى",
      "activityId": "60af884c2f9f9b1d2c8d9e13",
      "description": "استمارة لتسجيل الأبحاث الثقافية",
      "fields": [
        {
          "order": 1,
          "name": "عدد الابحاث",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 15,
            "maxNumber": 50,
            "nameTitle": "اسم الباحث",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    // الانشطة الكنسية : (60af884c2f9f9b1d2c8d9e16)
    /**
     * 1-> مسرح تقليدى - عدد الفرق - 50
     * 2-> مايم - عدد الفرق - 50
     * 3-> مونو دراما - عدد المشاركين - 50- اسم المشارك
     */
    {
      "_id": "664b48137565dd25fca12233",
      "name": "مسرح تقليدى",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل المسرح التقليدى",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12234",
      "name": "مسرح المايم",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل مسرح المايم",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12235",
      "name": "مونو دراما",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل المونو دراما",
      "fields": [
        {
          "order": 1,
          "name": "عدد المشاركين",
          "description": "ادخل عدد المشاركين",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 50,
            "maxNumber": 50,
            "nameTitle": "اسم المشارك",
            "minRequiredNames": 1,
            "maxRequiredNames": 1,
          },
        },
      ],
    },
    {
      "_id": "664b48137565dd25fca12236",
      "name": "ديو دراما",
      "activityId": "60af884c2f9f9b1d2c8d9e16",
      "description": "استمارة لتسجيل الديو دراما",
      "fields": [
        {
          "order": 1,
          "name": "عدد الفرق",
          "description": "ادخل عدد الفرق",
          "isRequired": false,
          "isNumber": true,
          "ifNumber": {
            "isPriced": true,
            "price": 100,
            "maxNumber": 50,
            "nameTitle": "الفريق",
            "minRequiredNames": 2,
            "maxRequiredNames": 2,
          },
        },
      ],
    },
  ];